### PR TITLE
Merge v0.60a into master

### PR DESCRIPTION
**Pull request by psociety**
Merge your latest stable release into master. So repo looks as up to date as it is.

### CODE REVIEW

**Comment by Felipefpl** [comment]
Hi irwir, i wanted ask why there are no issues tab for this? I want to report problems here instead of the forum.

**Comment by wdlkmpx** [comment]
Should be merged indeed

**Comment by irwir** [comment]
Master branch here keeps the original official eMule 0.50b code.

**Comment by Artoria2e5** [comment]
> Master branch here keeps the original official eMule 0.50b code.

You can change the default branch to "unofficial" in https://github.com/irwir/eMule/settings so people can see the actual code you are releasing. It's okay to keep the old master, but to show it as default is confusing.

(Don't click the link if you are not irwir. It won't work.)

**Pull request closed without merging**
